# Generated by Django 2.0.5 on 2018-06-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Markers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.IntegerField()),
                ('lng', models.IntegerField()),
                ('use_id', models.CharField(max_length=60)),
            ],
        ),
    ]
