# Generated by Django 2.0.5 on 2018-06-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markers',
            name='name',
            field=models.CharField(default='name', max_length=60),
        ),
        migrations.AddField(
            model_name='markers',
            name='type',
            field=models.CharField(default='type', max_length=60),
        ),
    ]
