# Generated by Django 2.0.5 on 2018-06-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20180608_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markers',
            name='type',
        ),
        migrations.AddField(
            model_name='markers',
            name='mktype',
            field=models.CharField(choices=[('m', 'museum'), ('s', 'school'), ('r', 'restaurant'), ('o', 'other')], default='museum', max_length=60),
        ),
    ]
