# Generated by Django 2.0.5 on 2018-06-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20180608_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='markers',
            name='address',
            field=models.CharField(default='address', max_length=100),
        ),
        migrations.AddField(
            model_name='markers',
            name='description',
            field=models.CharField(default='description', max_length=150),
        ),
    ]
