# Generated by Django 2.0.5 on 2018-06-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message',
        ),
    ]
